Repository PhrotonX/toDoListb4a, pull requests merged in 2025-03, with the labels that each got.

#6 Add editor layout
  EditorActivity.bas
  Files/editorlayout.bal
Labels: pull request, approved, resolved

#7 Update toDoListB4a
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#2 Create Main Layout
  EditorActivity.bas
  Files/editorlayout.bal
  Files/layout.bal
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#10 Feature/editor intent
  Bundle.bas
  EditorActivity.bas
  Starter.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#12 Add ToDo class
  ToDo.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#14 Add UI and sample logic for displaying item layout
  Files/layout.bal
  Files/todolistitemlayout.bal
  ToDoViewHolder.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#28 Add TaskRepository.bas
  TaskRepository.bas
  toDoListB4a.b4a
Labels: enhancement, approved, resolved

#15 Add ToDoDatabase.bas
  DayOfTheWeek.bas
  DaysOfTheWeek.bas
  Repeat.bas
  Starter.bas
  TaskRepository.bas
  TaskViewModel.bas
  ToDo.bas
  ToDoDatabase.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#30 -Settings button added
  Files/layout.bal
  Files/settingsabout.bal
  Files/settingshelp.bal
  Files/settingslayout.bal
  Files/sviewlayout.bal
  SettingsAbout.bas
  SettingsActivity.bas
  SettingsHelp.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#37 Phroton/fix repeat option
  ToDoDatabase.bas
Labels: pull request, approved, resolved

#34 UI changes 1
  EditorActivity.bas
  Files/editorlayout.bal
  Files/layout.bal
  Files/sviewlayout.bal
  Files/todolistitemlayout.bal
  SettingsActivity.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#38 UI changes
  EditorActivity.bas
  Files/editorlayout.bal
  Files/layout.bal
  Files/settingsabout.bal
  Files/settingshelp.bal
  Files/settingslayout.bal
  Files/sviewlayout.bal
  SettingsAbout.bas
  SettingsActivity.bas
  SettingsHelp.bas
  toDoListB4a.b4a
Labels: pull request, approved, wip

#41 Fix loading issues causing duplicated item on MainActivity
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#8 Dev: v0.1.0.1 alpha
  Bundle.bas
  DayOfTheWeek.bas
  DaysOfTheWeek.bas
  EditorActivity.bas
  Files/editorlayout.bal
  Files/layout.bal
  Files/settingsabout.bal
  Files/settingshelp.bal
  Files/settingslayout.bal
  Files/sviewlayout.bal
  Files/taskitemlayout.bal
  Repeat.bas
  SettingsAbout.bas
  SettingsActivity.bas
  SettingsHelp.bas
  Starter.bas
  TaskRepository.bas
  TaskViewHolder.bas
  TaskViewModel.bas
  ToDo.bas
  ToDoDatabase.bas
  ToDoViewHolder.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#47 Fix task insert and update issues on Database
  ToDoDatabase.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#49 Feature/task toggle
  Files/layout.bal
  Files/taskitemlayout.bal
  TaskViewHolder.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#50 Add glance information for tasks
  DaysOfTheWeek.bas
  ToDo.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#48 Dev: v0.1.0.2 alpha
  DaysOfTheWeek.bas
  Files/layout.bal
  Files/taskitemlayout.bal
  TaskViewHolder.bas
  ToDo.bas
  ToDoDatabase.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#51 v0.1.0 release
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#43 0.1.0 - Initial Release
  Bundle.bas
  DayOfTheWeek.bas
  DaysOfTheWeek.bas
  EditorActivity.bas
  Files/editorlayout.bal
  Files/layout.bal
  Files/settingsabout.bal
  Files/settingshelp.bal
  Files/settingslayout.bal
  Files/sviewlayout.bal
  Files/taskitemlayout.bal
  Repeat.bas
  SettingsAbout.bas
  SettingsActivity.bas
  SettingsHelp.bas
  Starter.bas
  TaskRepository.bas
  TaskViewHolder.bas
  TaskViewModel.bas
  ToDo.bas
  ToDoDatabase.bas
  ToDoViewHolder.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#55 Code cleanup
  Bundle.bas
  DayOfTheWeek.bas
  DaysOfTheWeek.bas
  Repeat.bas
  ToDoViewHolder.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#57 taskViewLayout
  EditorActivity.bas
  Files/editorlayout.bal
  Files/settingsabout.bal
  Files/settingshelp.bal
  Files/settingslayout.bal
  Files/taskitemlayout.bal
  Files/taskviewlayout.bal
  toDoListB4a.b4a
  viewActivity.bas
Labels: pull request, approved, resolved

#62 Improve code for Database
  ToDoDatabase.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#60 Feature/improve UI
  EditorActivity.bas
  Files/taskitemlayout.bal
  Files/taskviewlayout.bal
  Files/taskviewscrolllayout.bal
  Starter.bas
  TaskViewerActivity.bas
  ToDoDatabase.bas
  toDoListB4a.b4a
Labels: documentation, pull request, approved, resolved

#61 UI task hold
  Files/editorlayout.bal
  Files/settingslayout.bal
  Files/taskitemlayoutold.bal
  toDoListB4a.b4a
  viewActivity.bas
Labels: pull request, wip

#65 Feature/new editor UI
  Files/editorscrolllayout.bal
Labels: pull request, approved, resolved

#68 Feature/fnl changes
  EditorActivity.bas
  Files/aboutitems.bal
  Files/editorlayout.bal
  Files/editorscrolllayout.bal
  Files/helpitems.bal
  Files/layout.bal
  Files/settingsabout.bal
  Files/settingshelp.bal
  Files/settingslayout.bal
  Files/sviewlayout.bal
  Files/taskitemlayout.bal
  Files/taskviewlayout.bal
  Files/taskviewscrolllayout.bal
  SettingsAbout.bas
  SettingsActivity.bas
  SettingsHelp.bas
  TaskViewerActivity.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#69 Fix/due date bugs
  EditorActivity.bas
  Files/editorscrolllayout.bal
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#74 Fix/UI issues
  Date.bas
  Files/editorscrolllayout.bal
  Files/taskitemlayout.bal
  Files/taskviewscrolllayout.bal
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#77 Fix bug preventing the app from inserting due date data.
  ToDoDatabase.bas
Labels: pull request, approved, resolved

#78 Fix touch style issues for TaskViewHolders within MainActivity.
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#75 Dev: v1.0.0-alpha.2
  Date.bas
  Files/editorscrolllayout.bal
  Files/taskitemlayout.bal
  Files/taskviewscrolllayout.bal
  ToDoDatabase.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#80 Feature/app icon
  Files/aboutitems.bal
  Files/editorscrolllayout.bal
  Files/ic_launcher.png
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#81 Dev: v1.0.0.3 alpha
  Files/aboutitems.bal
  Files/editorscrolllayout.bal
  Files/ic_launcher.png
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#84 Fix/empty taskvieweractivity
  Date.bas
  TaskViewerActivity.bas
  ToDo.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#85 Update documentation
  TaskViewerActivity.bas
Labels: pull request, approved, resolved

#86 Dev: v1.0.0.4 alpha
  Date.bas
  TaskViewerActivity.bas
  ToDo.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#89 Fix blurry app icon on about page.
  Files/aboutitems.bal
  Files/ic_launcher_xl.png
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#91 Fix EditorActivity not renaming title bar into Edit Task while editing
  EditorActivity.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#93 Fix incorrect validation message for having empty due date year field
  EditorActivity.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved
