Repository PhrotonX/toDoListb4a, pull requests merged in 2025-04, with the labels that each got.

#134 Feature/sorting
  TaskRepository.bas
  TaskViewModel.bas
  ToDoDatabase.bas
Labels: pull request, approved, resolved

#138 Feature/searching
  TaskRepository.bas
  TaskViewModel.bas
  ToDoDatabase.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#142 Add MainActivity modes
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#147 Feature/dao
  DatabaseUtils.bas
  TaskDao.bas
  TaskRepository.bas
  ToDoDatabase.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#150 feature/attachment-upload-2
  Files/3528206.png
  Files/attachmentviewholder.bal
Labels: pull request, approved, resolved

#149 feature/attachment-upload
  Files/3528206.png
  Files/attachmentviewholder.bal
  Files/editorscrolllayout.bal
  Files/folder.png
  toDoListB4a.b4a
Labels: pull request, under review

#155 Feature/todo filesystem
  Attachment.bas
  AttachmentDao.bas
  AttachmentFileRepository.bas
  AttachmentRepository.bas
  AttachmentViewModel.bas
  EditorActivity.bas
  Starter.bas
  ToDo.bas
  ToDoDatabase.bas
  ToDoFileSystem.bas
  tatus
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#152 Feature/attachments logic
  Attachment.bas
  AttachmentDao.bas
  AttachmentFileRepository.bas
  AttachmentRepository.bas
  AttachmentViewModel.bas
  EditorActivity.bas
  FileUtils.bas
  Starter.bas
  TaskDao.bas
  ToDo.bas
  ToDoDatabase.bas
  ToDoFileSystem.bas
  tatus
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#157 search, nav drawer, ui changes
  Files/486023921_623831243812785_3842496593750662642_n.jpg
  Files/draweritems.bal
  Files/drawerlayout.bal
  Files/emptytasks.bal
  Files/layout.bal
  Files/newfragment.bal
  Files/separatorlayout.bal
  Files/solid_white.png
  initialscreen.bas
  toDoListB4a.b4a
Labels: pull request, under review

#135 Dev: v2.0.0.1 alpha
  Attachment.bas
  AttachmentDao.bas
  AttachmentFileRepository.bas
  AttachmentRepository.bas
  AttachmentViewHolder.bas
  AttachmentViewModel.bas
  DatabaseUtils.bas
  Date.bas
  DateAndTime.bas
  Dimen.bas
  EditorActivity.bas
  FileUtils.bas
  Files/3528206.png
  Files/486023921_623831243812785_3842496593750662642_n.jpg
  Files/attachmentitemlayout.bal
  Files/canvas.bal
  Files/draweritems.bal
  Files/drawerlayout.bal
  Files/editorlayout.bal
  Files/editorscrolllayout.bal
  Files/emptytasks.bal
  Files/folder.png
  Files/layout.bal
  Files/newfragment.bal
  Files/pencil.png
  Files/separatorlayout.bal
  Files/solid_white.png
  Files/taskviewscrolllayout.bal
  Starter.bas
  TaskDao.bas
  TaskRepository.bas
  TaskViewModel.bas
  TaskViewerActivity.bas
  Theme.bas
  Time.bas
  ToDo.bas
  ToDoDatabase.bas
  ToDoFileSystem.bas
  initialscreen.bas
  tatus
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#166 feature/addGroupTask
  Files/sviewlayout.bal
  SettingsActivity.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#168 Fix problematic naming convention within layout file of Settings layout and SettingsActivity
  Files/sviewlayout.bal
  SettingsActivity.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#170 Prototype code for opening attachments.
  AttachmentViewModel.bas
  EditorActivity.bas
  ToDoDatabase.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#171 Feature/task group backend
  AttachmentFileRepository.bas
  AttachmentViewModel.bas
  EditorActivity.bas
  Group.bas
  GroupDao.bas
  GroupRepository.bas
  GroupViewModel.bas
  TaskDao.bas
  ToDoDatabase.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#175 Feature/get tasks from group
  Group.bas
  TaskDao.bas
  TaskRepository.bas
  TaskViewModel.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#174 Feature/task group logic
  Files/draweritems.bal
  Group.bas
  GroupViewHolder.bas
  Starter.bas
  TaskDao.bas
  TaskRepository.bas
  TaskViewModel.bas
  ToDoDatabase.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#178 Feature/planned list subgroups
  Files/taskitemlayout.bal
  SubGroupViewHolder.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#186 Feature/completed tasks
  TaskDao.bas
  TaskRepository.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#184 addReminder
  Files/taskviewscrolllayout.bal
Labels: pull request, approved, resolved

#188 Revert "addReminder"
  Files/taskviewscrolllayout.bal
Labels: pull request, approved, resolved

#183 TaskGroupEditor
  Files/editorscrolllayout.bal
Labels: pull request, approved, resolved

#191 Fix the margin slightly for reminder field
  Files/editorscrolllayout.bal
Labels: pull request, approved, resolved

#187 Feature/task group logic
  TaskDao.bas
  TaskRepository.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#195 Change Debug Button to Toggle Switch
  Files/sviewlayout.bal
  SettingsActivity.bas
Labels: pull request, approved, under review

#198 Feature/task group edit
  EditorActivity.bas
  GroupDao.bas
  GroupRepository.bas
  GroupViewModel.bas
  Starter.bas
  TaskViewerActivity.bas
  ToDoDatabase.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#199 improvement/taskviewer
  Files/editorscrolllayout.bal
  Files/taskviewscrolllayout.bal
Labels: pull request, approved, resolved

#201 Add information for task group on task viewer
  GroupViewModel.bas
  TaskViewerActivity.bas
Labels: pull request, approved, resolved

#167 Dev: v2.0.0.2 alpha
  AttachmentFileRepository.bas
  AttachmentViewModel.bas
  EditorActivity.bas
  Files/draweritems.bal
  Files/editorscrolllayout.bal
  Files/sviewlayout.bal
  Files/taskitemlayout.bal
  Files/taskviewscrolllayout.bal
  Group.bas
  GroupDao.bas
  GroupRepository.bas
  GroupViewHolder.bas
  GroupViewModel.bas
  SettingsActivity.bas
  Starter.bas
  SubGroupViewHolder.bas
  TaskDao.bas
  TaskRepository.bas
  TaskViewModel.bas
  TaskViewerActivity.bas
  ToDoDatabase.bas
  toDoListB4a.b4a
Labels: pull request, approved, wip

#203 Add backend for settings
  SettingsRepository.bas
  SettingsViewModel.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#205 Feature/search sort upd
  Files/486023921_623831243812785_3842496593750662642_n (1).png
  Files/486023921_623831243812785_3842496593750662642_n.jpg
  Files/drawerlayout.bal
  Files/layout.bal
  Files/newfragment.bal
  Files/searchbylayout.bal
  Files/settingslayout.bal
  Files/stock4.png
  Files/taskitemlayout.bal
  Files/test.bal
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#206 Feature/settings logic
  AttachmentFileRepository.bas
  AttachmentViewModel.bas
  EditorActivity.bas
  SettingsActivity.bas
  SettingsRepository.bas
  SettingsViewModel.bas
  Starter.bas
  ToDoDatabase.bas
  ToDoDatabaseViewModel.bas
  ToDoFileSystem.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#214 Add sorting logic
  TaskDao.bas
  TaskQuery.bas
  TaskRepository.bas
  TaskViewModel.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#216 Add the ability to open attachments
  AttachmentFileRepository.bas
  AttachmentViewModel.bas
  EditorActivity.bas
  Starter.bas
  ToDoFileSystem.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#226 Fix transitive dependency within task_repeat table.
  DaysOfTheWeek.bas
  EditorActivity.bas
  Repeat.bas
  RepeatDao.bas
  RepeatRepository.bas
  RepeatViewModel.bas
  Starter.bas
  TaskDao.bas
  TaskViewModel.bas
  TaskViewerActivity.bas
  ToDo.bas
  ToDoDatabase.bas
  ToDoDatabaseViewModel.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#225 -fixed colors
  Files/blue-selected.png
  Files/blue.png
  Files/green-selected.png
  Files/green.png
  Files/grouptaskssvlayout.bal
  Files/indigo-selected.png
  Files/indigo.png
  Files/orange-selected.png
  Files/orange.png
  Files/pink-selected.png
  Files/pink.png
  Files/red-selected.png
  Files/red.png
  Files/searchfragmentsvlayout.bal
  Files/yellow-selected.png
  Files/yellow.png
  TaskGroupActivity.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#224 Feature/grouptasks
  Files/aboutitems.bal
  Files/attachmentitemlayout.bal
  Files/blue-selected.png
  Files/blue.png
  Files/canvas.bal
  Files/draweritems.bal
  Files/drawerlayout.bal
  Files/editorlayout.bal
  Files/emptytasks.bal
  Files/green-selected.png
  Files/green.png
  Files/grouptaskslayout.bal
  Files/grouptaskssvlayout.bal
  Files/helpitems.bal
  Files/indigo-selected.png
  Files/indigo.png
  Files/layout.bal
  Files/newfragment.bal
  Files/orange-selected.png
  Files/orange.png
  Files/pink-selected.png
  Files/pink.png
  Files/red-selected.png
  Files/red.png
  Files/searchbylayout.bal
  Files/searchfragmentlayout.bal
  Files/searchfragmentsvlayout.bal
  Files/separatorlayout.bal
  Files/settingsabout.bal
  Files/settingshelp.bal
  Files/settingslayout.bal
  Files/sviewlayout.bal
  Files/taskitemlayout.bal
  Files/taskviewlayout.bal
  Files/yellow-selected.png
  Files/yellow.png
  TaskGroupActivity.bas
  groupTasksActivity.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#247 overlapissueFix
  Files/editorscrolllayout.bal
Labels: pull request, approved, resolved

#237 align
  Files/editorscrolllayout.bal
  Files/taskviewscrolllayout.bal
Labels: pull request, approved, resolved

#254 Feature/notifications
  Date.bas
  EditorActivity.bas
  Files/ic_launcher_small.png
  Repeat.bas
  RepeatDao.bas
  RepeatRepository.bas
  RepeatViewModel.bas
  SettingsActivity.bas
  SettingsRepository.bas
  SettingsViewModel.bas
  Snooze.bas
  Starter.bas
  TaskDao.bas
  TaskNotification.bas
  TaskNotificationCompat.bas
  TaskNotificationCompleteReceiver.bas
  TaskNotificationDismissReceiver.bas
  TaskNotificationScheduler.bas
  TaskNotificationService.bas
  TaskNotificationSnoozeReceiver.bas
  Time.bas
  ToDo.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#259 Feature/notification backend
  Repeat.bas
  RepeatDao.bas
  RepeatViewModel.bas
  TaskNotificationCompleteReceiver.bas
  TaskNotificationService.bas
  TaskViewModel.bas
  TaskViewerActivity.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#233 Feature/reminders logic
  DateAndTime.bas
  EditorActivity.bas
  Repeat.bas
  RepeatDao.bas
  RepeatRepository.bas
  RepeatViewModel.bas
  TaskNotificationCompleteReceiver.bas
  TaskNotificationDismissReceiver.bas
  TaskNotificationScheduler.bas
  TaskNotificationService.bas
  TaskNotificationSnoozeReceiver.bas
  TaskRepository.bas
  TaskViewModel.bas
  TaskViewerActivity.bas
  Time.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#252 Dev: v2.0.0.4 alpha
  Date.bas
  DateAndTime.bas
  EditorActivity.bas
  Files/editorscrolllayout.bal
  Files/ic_launcher_small.png
  Files/taskviewscrolllayout.bal
  Repeat.bas
  RepeatDao.bas
  RepeatRepository.bas
  RepeatViewModel.bas
  SettingsActivity.bas
  SettingsRepository.bas
  SettingsViewModel.bas
  Snooze.bas
  Starter.bas
  TaskDao.bas
  TaskNotification.bas
  TaskNotificationCompat.bas
  TaskNotificationCompleteReceiver.bas
  TaskNotificationDismissReceiver.bas
  TaskNotificationScheduler.bas
  TaskNotificationService.bas
  TaskNotificationSnoozeReceiver.bas
  TaskRepository.bas
  TaskViewModel.bas
  TaskViewerActivity.bas
  Time.bas
  ToDo.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#270 Feature/taskviewer attachments
  AttachmentViewModel.bas
  EditorActivity.bas
  Files/attachmentlistlayout.bal
  TaskViewerActivity.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#272 drawer items bugfix
  Files/drawerlayout.bal
  Files/editorscrolllayout.bal
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#278 Feature/default group
  TaskDao.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#284 Feature/task group editor logic
  Group.bas
  GroupDao.bas
  Starter.bas
  TaskGroupActivity.bas
  Theme.bas
  ToDoDatabase.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#286 Feature/task group
  Files/draweritems.bal
  Files/grouptaskslayout.bal
  Files/grouptaskssvlayout.bal
  Files/layout.bal
  Files/searchfragmentlayout.bal
  Files/searchfragmentsvlayout.bal
  TaskGroupActivity.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#287 Feature/fix task query
  EditorActivity.bas
  TaskDao.bas
  TaskQuery.bas
  TaskRepository.bas
  TaskViewModel.bas
Labels: pull request, approved, resolved

#285 Add functionality for Task Group Editor
  EditorActivity.bas
Labels: pull request, wip, resolved
