Repository PhrotonX/toDoListb4a, pull requests merged in 2025-05, with the labels that each got.

#288 Update documentation for EditorActivity.bas
  EditorActivity.bas
Labels: pull request, approved, resolved

#274 Dev: v2.0.0.5 alpha
  AttachmentViewModel.bas
  EditorActivity.bas
  Files/aboutitems.bal
  Files/attachmentitemlayout.bal
  Files/attachmentlistlayout.bal
  Files/canvas.bal
  Files/draweritems.bal
  Files/drawerlayout.bal
  Files/editorscrolllayout.bal
  Files/emptytasks.bal
  Files/grouptaskslayout.bal
  Files/grouptaskssvlayout.bal
  Files/helpitems.bal
  Files/layout.bal
  Files/newfragment.bal
  Files/searchfragmentlayout.bal
  Files/searchfragmentsvlayout.bal
  Files/separatorlayout.bal
  Files/settingsabout.bal
  Files/settingshelp.bal
  Files/settingslayout.bal
  Files/sviewlayout.bal
  Files/taskitemlayout.bal
  Group.bas
  GroupDao.bas
  SettingsActivity.bas
  Starter.bas
  TaskDao.bas
  TaskGroupActivity.bas
  TaskQuery.bas
  TaskRepository.bas
  TaskViewModel.bas
  TaskViewerActivity.bas
  Theme.bas
  ToDoDatabase.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#293 Feature/search naming convention changes
  EditorActivity.bas
  Files/attachmentitemlayout.bal
  Files/editorscrolllayout.bal
  Files/searchfragmentsvlayout.bal
  TaskGroupActivity.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#297 improve ui for task view layout
  Files/taskviewlayout.bal
  Files/taskviewscrolllayout.bal
Labels: pull request

#299 Fix crash when saving a new task
  EditorActivity.bas
  toDoListB4a.b4a
Labels: pull request, wip

#301 Move some validation and field population logic from EditorActivity into FormHelper
  EditorActivity.bas
  FormHelper.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#300 changed colors along with spinner colors
  EditorActivity.bas
  Files/editorlayout.bal
  Files/editorscrolllayout.bal
Labels: pull request, wip, under review

#308 Feature/add task rework
  EditorActivity.bas
  Files/attachmentitemlayout.bal
  Files/editorlayout.bal
  Files/editorscrolllayout.bal
Labels: pull request, approved, resolved

#263 Major settings improvements
  Files/settingslayout.bal
  Files/sviewlayout.bal
  SettingsActivity.bas
  toDoListB4a.b4a
Labels: pull request, resolved, under review

#309 Feature/form helper
  EditorActivity.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#310 Add basic searching and fix some issues
  EditorActivity.bas
  Files/newfragment.bal
  Files/settingslayout.bal
  Files/sviewlayout.bal
  FormHelper.bas
  SettingsActivity.bas
  TaskQuery.bas
  TaskViewModel.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#312 Style task view layout
  Files/taskviewlayout.bal
  Files/taskviewscrolllayout.bal
Labels: pull request, approved, resolved

#314 Feature/task query join statement
  TaskDao.bas
  TaskQuery.bas
  TaskRepository.bas
  TaskViewModel.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#317 Add searching logic
  EditorActivity.bas
  FormHelper.bas
  TaskDao.bas
  TaskQuery.bas
  TaskRepository.bas
  TaskViewModel.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#296 Dev: v2.0.0.6 alpha
  EditorActivity.bas
  Files/attachmentitemlayout.bal
  Files/editorlayout.bal
  Files/editorscrolllayout.bal
  Files/grouptaskslayout.bal
  Files/grouptaskssvlayout.bal
  Files/layout.bal
  Files/newfragment.bal
  Files/searchfragmentsvlayout.bal
  Files/settingslayout.bal
  Files/sviewlayout.bal
  Files/taskviewlayout.bal
  Files/taskviewscrolllayout.bal
  FormHelper.bas
  SettingsActivity.bas
  TaskDao.bas
  TaskGroupActivity.bas
  TaskQuery.bas
  TaskRepository.bas
  TaskViewModel.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#334 Fix bug causing a crash when setting the due date day value into anyt…
  EditorActivity.bas
Labels: pull request, approved, resolved

#335 Feature/search by date range
  Date.bas
  FormHelper.bas
  TaskQuery.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#336 Feature/task group revisions
  Files/brown-selected.png
  Files/brown.png
  Files/orange-selected.png
  Files/orange.png
  Files/pink-selected.png
  Files/pink.png
  Files/red-selected.png
  Files/red.png
  Files/yellow-selected.png
  Files/yellow.png
  TaskGroupActivity.bas
  TaskViewModel.bas
  ToDoDatabase.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#327 Dev: v2.0.0.7 alpha
  Date.bas
  EditorActivity.bas
  Files/brown-selected.png
  Files/brown.png
  Files/layout.bal
  Files/orange-selected.png
  Files/orange.png
  Files/pink-selected.png
  Files/pink.png
  Files/red-selected.png
  Files/red.png
  Files/yellow-selected.png
  Files/yellow.png
  FormHelper.bas
  Group.bas
  GroupDao.bas
  TaskGroupActivity.bas
  TaskQuery.bas
  TaskViewModel.bas
  Theme.bas
  ToDoDatabase.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#337 Fix missing attachment list changes
  AttachmentViewHolder.bas
  EditorActivity.bas
  Files/attachmentitemlayout.bal
  Files/attachmentlistlayout.bal
  Files/editorscrolllayout.bal
  TaskViewerActivity.bas
Labels: pull request, approved, resolved

#338 Dev: Additional v2.0.0.7 changes
  AttachmentViewHolder.bas
  EditorActivity.bas
  Files/attachmentitemlayout.bal
  Files/attachmentlistlayout.bal
  Files/editorscrolllayout.bal
  TaskViewerActivity.bas
Labels: pull request, approved, resolved

#346 Feature/task group editor improvements
  GroupDao.bas
  GroupRepository.bas
  GroupViewModel.bas
  TaskGroupActivity.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#344 fix truncated repeat options
  AttachmentViewHolder.bas
  Date.bas
  EditorActivity.bas
  Files/486023921_623831243812785_3842496593750662642_n.jpg
  Files/attachmentitemlayout.bal
  Files/attachmentlistlayout.bal
  Files/brown-selected.png
  Files/brown.png
  Files/draweritems.bal
  Files/editorlayout.bal
  Files/editorscrolllayout.bal
  Files/grouptaskslayout.bal
  Files/grouptaskssvlayout.bal
  Files/layout.bal
  Files/newfragment.bal
  Files/orange-selected.png
  Files/orange.png
  Files/pink-selected.png
  Files/pink.png
  Files/red-selected.png
  Files/red.png
  Files/searchfragmentlayout.bal
  Files/searchfragmentsvlayout.bal
  Files/settingslayout.bal
  Files/sviewlayout.bal
  Files/taskviewlayout.bal
  Files/taskviewscrolllayout.bal
  Files/yellow-selected.png
  Files/yellow.png
  FormHelper.bas
  Group.bas
  GroupDao.bas
  SettingsActivity.bas
  Starter.bas
  TaskDao.bas
  TaskGroupActivity.bas
  TaskQuery.bas
  TaskRepository.bas
  TaskViewModel.bas
  TaskViewerActivity.bas
  Theme.bas
  ToDoDatabase.bas
  toDoListB4a.b4a
Labels: pull request

#348 Style editor layout
  Files/editorscrolllayout.bal
Labels: pull request, approved, resolved

#349 Add functionality into the menu refresh option and fix task group sta…
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#352 Fix/reminders bug
  EditorActivity.bas
  RepeatDao.bas
  TaskNotificationCompleteReceiver.bas
  TaskNotificationDismissReceiver.bas
  TaskNotificationScheduler.bas
  TaskNotificationService.bas
  TaskNotificationSnoozeReceiver.bas
Labels: pull request, wip

#354 Feature/task completion sound
  Files/done_sound.mp3
  SettingsActivity.bas
  TaskViewModel.bas
  TaskViewerActivity.bas
  credits.txt
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#347 Dev: 2.0.0.8 alpha
  EditorActivity.bas
  Files/486023921_623831243812785_3842496593750662642_n.jpg
  Files/done_sound.mp3
  Files/editorscrolllayout.bal
  Files/layout.bal
  Files/newfragment.bal
  Files/settingslayout.bal
  Files/sviewlayout.bal
  Files/taskviewlayout.bal
  Files/taskviewscrolllayout.bal
  GroupDao.bas
  GroupRepository.bas
  GroupViewModel.bas
  RepeatDao.bas
  SettingsActivity.bas
  TaskGroupActivity.bas
  TaskNotificationCompleteReceiver.bas
  TaskNotificationDismissReceiver.bas
  TaskNotificationScheduler.bas
  TaskNotificationService.bas
  TaskNotificationSnoozeReceiver.bas
  TaskViewModel.bas
  TaskViewerActivity.bas
  credits.txt
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#358 Fix several sorting issues.
  TaskRepository.bas
  TaskViewModel.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#360 Feature/search task item info
  AttachmentDao.bas
  AttachmentRepository.bas
  AttachmentViewModel.bas
  Files/en_us.json
  SettingsActivity.bas
  SettingsRepository.bas
  SettingsViewModel.bas
  TaskGroupActivity.bas
  TaskQuery.bas
  ToDo.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#361 added an empty task layout
  AdvancedSettingsActivity.bas
  Files/emptytasks.bal
  Files/newfragment.bal
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#371 Feature/language
  AdvancedSettingsActivity.bas
  Files/ar.json
  Files/en-us.json
  Files/es-ES.json
  Files/id-ID.json
  Files/pam.json
  Files/ru-RU.json
  Files/tl-PH.json
  Files/zh-cn.json
  LanguageManager.bas
  SettingsActivity.bas
  Starter.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#372 Fix project file
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#374 changed color for editor, viewer, addgrp, search
  AdvancedSettingsActivity.bas
  Files/attachmentitemlayout.bal
  Files/draweritems.bal
  Files/drawerlayout.bal
  Files/editorlayout.bal
  Files/editorscrolllayout.bal
  Files/emptytasks.bal
  Files/grouptaskslayout.bal
  Files/grouptaskssvlayout.bal
  Files/layout.bal
  Files/taskitemlayout.bal
  Files/taskviewlayout.bal
  Files/taskviewscrolllayout.bal
  TaskViewerActivity.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#359 Dev: v2.0.0.9 alpha
  AdvancedSettingsActivity.bas
  AttachmentDao.bas
  AttachmentRepository.bas
  AttachmentViewModel.bas
  Date.bas
  DateAndTime.bas
  DaysOfTheWeek.bas
  EditorActivity.bas
  FileUtils.bas
  Files/advancedsettingslayout.bal
  Files/ar.json
  Files/attachmentitemlayout.bal
  Files/draweritems.bal
  Files/drawerlayout.bal
  Files/editorlayout.bal
  Files/editorscrolllayout.bal
  Files/emptytasks.bal
  Files/en-us.json
  Files/es-ES.json
  Files/grouptaskslayout.bal
  Files/grouptaskssvlayout.bal
  Files/id-ID.json
  Files/layout.bal
  Files/newfragment.bal
  Files/pam.json
  Files/ru-RU.json
  Files/smiley.png
  Files/sviewlayout.bal
  Files/taskitemlayout.bal
  Files/taskviewlayout.bal
  Files/taskviewscrolllayout.bal
  Files/tl-PH.json
  Files/zh-cn.json
  FormHelper.bas
  LanguageManager.bas
  Repeat.bas
  RepeatDao.bas
  SettingsAbout.bas
  SettingsActivity.bas
  SettingsHelp.bas
  SettingsRepository.bas
  SettingsViewModel.bas
  Snooze.bas
  Starter.bas
  SubGroupViewHolder.bas
  TaskGroupActivity.bas
  TaskNotificationCompleteReceiver.bas
  TaskNotificationDismissReceiver.bas
  TaskNotificationScheduler.bas
  TaskNotificationService.bas
  TaskNotificationSnoozeReceiver.bas
  TaskQuery.bas
  TaskRepository.bas
  TaskViewModel.bas
  TaskViewerActivity.bas
  ToDo.bas
  ToDoDatabase.bas
  ToDoDatabaseViewModel.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#378 help and about added back to settings
  Files/aboutitems.bal
  Files/emptytasks.bal
  Files/helpitems.bal
  Files/layout.bal
  Files/settingsabout.bal
  Files/settingshelp.bal
  Files/sviewlayout.bal
  SettingsAbout.bas
  SettingsActivity.bas
  SettingsHelp.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#385 Style editor layout
  Files/editorscrolllayout.bal
Labels: pull request, approved, resolved

#386 Feature/improve back button
  AdvancedSettingsActivity.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#389 App stability
  AdvancedSettingsActivity.bas
  EditorActivity.bas
  Files/aboutitems.bal
  Files/advancedsettingslayout.bal
  Files/drawerlayout.bal
  Files/editorlayout.bal
  Files/editorscrolllayout.bal
  Files/emptytasks.bal
  Files/grouptaskslayout.bal
  Files/grouptaskssvlayout.bal
  Files/helpitems.bal
  Files/newfragment.bal
  Files/searchfragmentsvlayout.bal
  Files/settingsabout.bal
  Files/settingshelp.bal
  Files/settingslayout.bal
  Files/sviewlayout.bal
  Files/taskviewlayout.bal
  Files/taskviewscrolllayout.bal
  RepeatViewModel.bas
  SettingsActivity.bas
  TaskGroupActivity.bas
  TaskNotificationSnoozeReceiver.bas
  TaskViewModel.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#379 Dev: v2.0.0.10 alpha
  AdvancedSettingsActivity.bas
  EditorActivity.bas
  Files/aboutitems.bal
  Files/advancedsettingslayout.bal
  Files/drawercolorlight.png
  Files/drawerlayout.bal
  Files/editorlayout.bal
  Files/editorscrolllayout.bal
  Files/emptytasks.bal
  Files/grouptaskslayout.bal
  Files/grouptaskssvlayout.bal
  Files/helpitems.bal
  Files/layout.bal
  Files/newfragment.bal
  Files/searchfragmentsvlayout.bal
  Files/settingsabout.bal
  Files/settingshelp.bal
  Files/settingslayout.bal
  Files/sviewlayout.bal
  Files/taskviewlayout.bal
  Files/taskviewscrolllayout.bal
  RepeatViewModel.bas
  SettingsAbout.bas
  SettingsActivity.bas
  SettingsHelp.bas
  SettingsViewModel.bas
  Starter.bas
  TaskGroupActivity.bas
  TaskNotificationSnoozeReceiver.bas
  TaskViewModel.bas
  TaskViewerActivity.bas
  Theme.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#393 Finalize
  EditorActivity.bas
  Files/aboutitems.bal
  Files/ar.json
  Files/attachmentitemlayout.bal
  Files/editorscrolllayout.bal
  Files/en-us.json
  Files/es-ES.json
  Files/grouptaskssvlayout.bal
  Files/id-ID.json
  Files/pam.json
  Files/ru-RU.json
  Files/taskviewscrolllayout.bal
  Files/tl-PH.json
  Files/zh-cn.json
  FormHelper.bas
  SettingsAbout.bas
  SettingsRepository.bas
  SettingsViewModel.bas
  TaskGroupActivity.bas
  TaskViewModel.bas
  TaskViewerActivity.bas
  Theme.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#394 Dev: v2.0.0.11 alpha
  EditorActivity.bas
  Files/aboutitems.bal
  Files/ar.json
  Files/attachmentitemlayout.bal
  Files/editorscrolllayout.bal
  Files/en-us.json
  Files/es-ES.json
  Files/grouptaskssvlayout.bal
  Files/id-ID.json
  Files/pam.json
  Files/ru-RU.json
  Files/taskviewscrolllayout.bal
  Files/tl-PH.json
  Files/zh-cn.json
  FormHelper.bas
  SettingsAbout.bas
  SettingsRepository.bas
  SettingsViewModel.bas
  TaskGroupActivity.bas
  TaskViewModel.bas
  TaskViewerActivity.bas
  Theme.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#397 Hotfix/2.0.1
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  EditorActivity.bas
  Files/layout.bal
  documentation.md
  naming_convention.md
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#398 Dev: v2.0.1
  EditorActivity.bas
  Files/layout.bal
  toDoListB4a.b4a
Labels: pull request, approved, resolved

#400 Hotfix/v2.0.2
  Date.bas
  TaskQuery.bas
  toDoListB4a.b4a
Labels: pull request, approved, resolved
